WebAppGNAggregator/Controllers/ArticlesController.cs
using EFDatabase;
using EFDatabase.Entities;
using GNA.Services.Abstractions;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using DataConvert.DTO;
using Serilog;
using Mappers.Mappers;
using Microsoft.AspNetCore.Authorization;
using Microsoft.EntityFrameworkCore;


namespace WebAppGNAggregator.Controllers
{
    //[Authorize]
    public class ArticlesController : Controller
    {

        private readonly ILogger<HomeController> _logger;

        private readonly IArticleService _articleService;
        private readonly ISourceService _sourceService;
        private readonly IRssService _rssService;
        //private readonly GNAggregatorContext _dbContext;
        private readonly IServiceScopeFactory _scopeFactory;

        //private const int _sourceId = 1;

        private readonly ArticleMapper _articleMapper;


        public ArticlesController(ILogger<HomeController> logger,
            IArticleService articleService, 
            ISourceService sourceService,
            IRssService rssService, 
            ArticleMapper articleMapper, 
           // GNAggregatorContext dbContext,
            IServiceScopeFactory scopeFactory)
        {
            _logger = logger;
            _articleService = articleService;
            _articleMapper = articleMapper;
            _sourceService = sourceService;
            _rssService = rssService;
            //_dbContext = dbContext;
            _scopeFactory = scopeFactory;
        }


        public IActionResult Index()
        {
            _logger.LogInformation("Redirected to Home/Index");
            return RedirectToAction("Index", "Home");
        }


        [HttpGet]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Aggregate()
        {
            _logger.LogInformation("View 'Aggregate' loaded");
            return View();
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> AggregateProcessing(CancellationToken cancellationToken = default)
        {
            var sources = await _sourceService.GetSourceWithRssAsync(cancellationToken);
            var newArticles = new List<Article>();
            
            foreach (var source in sources)
            {
                var existedArticlesUrls = await _articleService.GetUniqueArticlesUrls(cancellationToken);
                _logger.LogInformation($"{source.Name} check ok");

                var articles = await _rssService.GetRssDataAsync(source, cancellationToken);
                _logger.LogInformation($"{source.Name} articles loaded from rss data");

                var newArticlesData = articles.Where(a => !existedArticlesUrls.Contains(a.Url)).ToArray();
                newArticles.AddRange(newArticlesData);
            }

            await _articleService.AddArticlesAsync(newArticles, cancellationToken);

            await _articleService.UpdateTextForArticlesByWebScrappingAsync(cancellationToken);

            _logger.LogInformation("Articles aggregated successfully");
            return RedirectToAction("Index", "Home");
        }


        [HttpPost]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Rate(CancellationToken cancellationToken = default) 
        {

            _ = Task.Run(async () =>
            {

                using var scope = _scopeFactory.CreateScope(); 
                var articleService = scope.ServiceProvider.GetRequiredService<IArticleService>();
                var logger = scope.ServiceProvider.GetRequiredService<ILogger<ArticlesController>>();

                logger.LogInformation("Articles rating process was started..... ");
                var isRated = await articleService.RatingProcess(cancellationToken);
                

                if (isRated)
                {
                    logger.LogInformation("Articles have been rated");
                }
                else
                {
                    logger.LogError("Error during rating articles");
                }
            }, cancellationToken);

            return RedirectToAction("Index", "Home");
        }


        [HttpGet]
        public async Task<IActionResult> Details(Guid id)
        {
            try
            {
                var articleDto = await _articleService.GetByIdAsync(id);

                if (articleDto != null)
                {
                    var articleModel = _articleMapper.ArticleDtoToArticleModel(articleDto);
                    
                    _logger.LogInformation($"Article {articleModel.Id} retrieved successfully.");
                    return View(articleModel);
                }
                else
                {
                    _logger.LogWarning($"Article {id} not found.");
                    throw new Exception();
                }
            }
            catch (Exception ex)
            {
                HttpContext.Response.StatusCode = 404;
                return RedirectToAction("Error", "Home", new
                {
                    statusCode = HttpContext.Response.StatusCode,
                    errorMessage = $"Такой новости нет :(<br>Почитайте что-нибудь ещё.<br><br>{ex.Message}"
                });
            }
        }



        [HttpPost]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(ArticleDto model)
        {
            try
            {
                var isDeleted = await _articleService.DeleteAsync(model.Id);

                if (isDeleted == true)
                {
                    _logger.LogInformation($"Article {model.Id} deleted successfully");
                    return RedirectToAction("Index", "Home");
                }
                else
                {
                    _logger.LogWarning($"Article {model.Id} not found");
                    //return RedirectToAction("Error", "Home", new { ErrorMessage = "Такой новости нет :(<br>Почитайте что-нибудь ещё", HttpContext.Response.StatusCode });
                    throw new Exception();
                }
            }
            catch (Exception ex)
            {
                HttpContext.Response.StatusCode = 404;
                return RedirectToAction("Error", "Home", new
                {
                    statusCode = HttpContext.Response.StatusCode,
                    errorMessage = "Такой новости нет :(<br>Почитайте что-нибудь ещё."
                });
            }
        }


        [HttpGet]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> EditArticle(Guid id)
        {
            try
            {
                var articleDto = await _articleService.GetByIdAsync(id);

                if (articleDto != null)
                {
                    var articleModel = _articleMapper.ArticleDtoToArticleModel(articleDto);
                    _logger.LogInformation($"Article {articleModel.Id} loaded for editing successfully");
                    return View(articleModel);
                }
                else
                {
                    _logger.LogWarning($"Article {id} for editing not found");
                    throw new Exception();
                }
            }
            catch (Exception ex)
            {
                HttpContext.Response.StatusCode = 404;
                return RedirectToAction("Error", "Home", new
                {
                    statusCode = HttpContext.Response.StatusCode,
                    errorMessage = "Такой новости нет :(<br>Почитайте что-нибудь ещё."
                });
            }
        }


        [HttpPost]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> EditArticle(ArticleModel model)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    _logger.LogWarning("Article edited model is not valid");
                    return View(model);
                }

                else
                {
                    var editedModel = _articleMapper.ArticleModelToArticleDto(model);
                    editedModel.Updated = DateTime.Now;
                    await _articleService.SaveChangedArticleAsync(editedModel);
                    _logger.LogInformation($"Article {model.Id} edited successfully");
                    return RedirectToAction("Index", "Home");
                }
            }
            catch (Exception ex)
            {
                HttpContext.Response.StatusCode = 404;
                return RedirectToAction("Error", "Home", new
                {
                    statusCode = HttpContext.Response.StatusCode,
                    errorMessage = "Такой новости нет :(<br>Почитайте что-нибудь ещё."
                });
            }
        }
    }
}

WebAppGNAggregator/Controllers/SourcesController.cs
using EFDatabase;
using GNA.Services.Abstractions;
using GNA.Services.Implementations;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.IdentityModel.Tokens;
//using DataConvert.Models;

namespace WebAppGNAggregator.Controllers
{
    public class SourcesController : Controller
    {
        private readonly ISourceService _sourceService;
        private readonly ILogger<HomeController> _logger;

        public SourcesController(ILogger<HomeController> logger,ISourceService sourceService)
        {
            _logger = logger;
            _sourceService = sourceService;
        }

        [HttpGet]
        public async Task<IActionResult> Index(CancellationToken cancellationToken = default)
        {
            try
            {
                var sources = await _sourceService.GetSourceWithRssAsync(cancellationToken);

                if (sources == null || sources.Length == 0)
                {
                    _logger.LogError("There are no sources with RSS");
                     throw new ArgumentNullException("Источники с RSS не найдены")  ;
                }
                else
                {
                    _logger.LogInformation("Sources with RSS successfully loaded");
                    return View(sources);
                }
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "An error occurred while loading sources");
                HttpContext.Response.StatusCode = 404;
                ViewBag.ErrorMessage = "Источники не найдены";
                throw;
            }
        }
    }
}

WebAppGNAggregator/Views/Home/Index.cshtml
@using System.Security.Claims
@model ArticleModelsCollection

@{
    ViewBag.Title = "Агрегатор хороших новостей";
    Layout = "_Layout";
}

<div>
    <ul class="highlighted shadow-lg" float=left id="currentTime"></ul>
</div>

<div>
    <h5>
        Элементов на странице:
        <a asp-action="Index" asp-route-page="@Model.PageInfo.PageNumber" asp-route-pageSize="15" class="@(Model.PageInfo.PageSize == 15 ? "active-link" : "")" style="@(Model.PageInfo.PageSize == 15 ? "style1" : "")">15</a>
        <a asp-action="Index" asp-route-page="@Model.PageInfo.PageNumber" asp-route-pageSize="30" class="@(Model.PageInfo.PageSize == 30 ? "active-link" : "")" style="@(Model.PageInfo.PageSize == 30 ? "style1" : "")">30</a>
        <a asp-action="Index" asp-route-page="@Model.PageInfo.PageNumber" asp-route-pageSize="50" class="@(Model.PageInfo.PageSize == 50 ? "active-link" : "")" style="@(Model.PageInfo.PageSize == 50 ? "style1" : "")">50</a>
    </h5>
</div>

<div>
    @if (User.Claims.Any(c => c.Type == ClaimTypes.Role && c.Value == "Admin"))
    {
        <a class="btn  btn400" asp-action="Aggregate" asp-controller="Articles">Администрирование новостей</a>
        <a class="btn  btn400" asp-action="Index" asp-controller="Sources">Список источников</a>
    }
</div>


<div class="container">
    <div class="row" data-masonry='{"percentPosition": true }'>
@foreach (var article in Model.ArticleModels)
{
    <div class="col-12 col-md-4 mb-3">
        <div class="cardGeneral shadow-lg">
            <div>
                <div class="card">@article.Title</div>
                <br>
                <h5>@article.Created</h5>
            </div>
            <div>
                <p>
                    @Html.Raw(article.Description)
                </p>
                <a asp-action="Details" asp-controller="Articles" asp-route-id="@article.Id">Подробнее</a>
            </div>
            <div>
                <h4>@article.SourceName</h4>
                <span>Rate: @article.PositivityRate</span>
            </div>
        </div>
    </div>
}

    </div>
</div>
<br>
<div class="d-flex justify-content-center">
    <pagination page-action="index" page-info="Model.PageInfo"></pagination>
</div>


<script>
    function updateTime()
    {
        var now = new Date();
        var options = {
            year: 'numeric',
            month: 'long',
            day: 'numeric',
            hour: 'numeric',
            minute: 'numeric',
            second: 'numeric',
            hour12: false
        };
        document.getElementById("currentTime").innerHTML = now.toLocaleString('ru-RU', options);
    }
    setInterval(updateTime, 500);
    updateTime();

</script>