WebAppGNAggregator/Controllers/ArticlesController.cs
using EFDatabase;
using EFDatabase.Entities;
using GNA.Services.Abstractions;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using DataConvert.DTO;
using Serilog;
using Mappers.Mappers;
using Microsoft.AspNetCore.Authorization;
using Microsoft.EntityFrameworkCore;


namespace WebAppGNAggregator.Controllers
{
    //[Authorize]
    public class ArticlesController : Controller
    {

        private readonly ILogger<HomeController> _logger;

        private readonly IArticleService _articleService;
        private readonly ISourceService _sourceService;
        private readonly IRssService _rssService;
        //private readonly GNAggregatorContext _dbContext;
        private readonly IServiceScopeFactory _scopeFactory;

        //private const int _sourceId = 1;

        private readonly ArticleMapper _articleMapper;


        public ArticlesController(ILogger<HomeController> logger,
            IArticleService articleService, 
            ISourceService sourceService,
            IRssService rssService, 
            ArticleMapper articleMapper, 
           // GNAggregatorContext dbContext,
            IServiceScopeFactory scopeFactory)
        {
            _logger = logger;
            _articleService = articleService;
            _articleMapper = articleMapper;
            _sourceService = sourceService;
            _rssService = rssService;
            //_dbContext = dbContext;
            _scopeFactory = scopeFactory;
        }


        public IActionResult Index()
        {
            _logger.LogInformation("Redirected to Home/Index");
            return RedirectToAction("Index", "Home");
        }


        [HttpGet]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Aggregate()
        {
            _logger.LogInformation("View 'Aggregate' loaded");
            return View();
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> AggregateProcessing(CancellationToken cancellationToken = default)
        {
            var sources = await _sourceService.GetSourceWithRssAsync(cancellationToken);
            var newArticles = new List<Article>();
            
            foreach (var source in sources)
            {
                var existedArticlesUrls = await _articleService.GetUniqueArticlesUrls(cancellationToken);
                _logger.LogInformation($"{source.Name} check ok");

                var articles = await _rssService.GetRssDataAsync(source, cancellationToken);
                _logger.LogInformation($"{source.Name} articles loaded from rss data");

                var newArticlesData = articles.Where(a => !existedArticlesUrls.Contains(a.Url)).ToArray();
                newArticles.AddRange(newArticlesData);
            }

            await _articleService.AddArticlesAsync(newArticles, cancellationToken);

            await _articleService.UpdateTextForArticlesByWebScrappingAsync(cancellationToken);

            _logger.LogInformation("Articles aggregated successfully");
            return RedirectToAction("Index", "Home");
        }


        [HttpPost]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Rate(CancellationToken cancellationToken = default) 
        {

            _ = Task.Run(async () =>
            {

                using var scope = _scopeFactory.CreateScope(); 
                var articleService = scope.ServiceProvider.GetRequiredService<IArticleService>();
                var logger = scope.ServiceProvider.GetRequiredService<ILogger<ArticlesController>>();

                logger.LogInformation("Articles rating process was started..... ");
                var isRated = await articleService.RatingProcess(cancellationToken);
                

                if (isRated)
                {
                    logger.LogInformation("Articles have been rated");
                }
                else
                {
                    logger.LogError("Error during rating articles");
                }
            }, cancellationToken);

            return RedirectToAction("Index", "Home");
        }


        [HttpGet]
        public async Task<IActionResult> Details(Guid id)
        {
            try
            {
                var articleDto = await _articleService.GetByIdAsync(id);

                if (articleDto != null)
                {
                    var articleModel = _articleMapper.ArticleDtoToArticleModel(articleDto);
                    
                    _logger.LogInformation($"Article {articleModel.Id} retrieved successfully.");
                    return View(articleModel);
                }
                else
                {
                    _logger.LogWarning($"Article {id} not found.");
                    throw new Exception();
                }
            }
            catch (Exception ex)
            {
                HttpContext.Response.StatusCode = 404;
                return RedirectToAction("Error", "Home", new
                {
                    statusCode = HttpContext.Response.StatusCode,
                    errorMessage = $"Такой новости нет :(<br>Почитайте что-нибудь ещё.<br><br>{ex.Message}"
                });
            }
        }



        [HttpPost]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(ArticleDto model)
        {
            try
            {
                var isDeleted = await _articleService.DeleteAsync(model.Id);

                if (isDeleted == true)
                {
                    _logger.LogInformation($"Article {model.Id} deleted successfully");
                    return RedirectToAction("Index", "Home");
                }
                else
                {
                    _logger.LogWarning($"Article {model.Id} not found");
                    //return RedirectToAction("Error", "Home", new { ErrorMessage = "Такой новости нет :(<br>Почитайте что-нибудь ещё", HttpContext.Response.StatusCode });
                    throw new Exception();
                }
            }
            catch (Exception ex)
            {
                HttpContext.Response.StatusCode = 404;
                return RedirectToAction("Error", "Home", new
                {
                    statusCode = HttpContext.Response.StatusCode,
                    errorMessage = "Такой новости нет :(<br>Почитайте что-нибудь ещё."
                });
            }
        }


        [HttpGet]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> EditArticle(Guid id)
        {
            try
            {
                var articleDto = await _articleService.GetByIdAsync(id);

                if (articleDto != null)
                {
                    var articleModel = _articleMapper.ArticleDtoToArticleModel(articleDto);
                    _logger.LogInformation($"Article {articleModel.Id} loaded for editing successfully");
                    return View(articleModel);
                }
                else
                {
                    _logger.LogWarning($"Article {id} for editing not found");
                    throw new Exception();
                }
            }
            catch (Exception ex)
            {
                HttpContext.Response.StatusCode = 404;
                return RedirectToAction("Error", "Home", new
                {
                    statusCode = HttpContext.Response.StatusCode,
                    errorMessage = "Такой новости нет :(<br>Почитайте что-нибудь ещё."
                });
            }
        }


        [HttpPost]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> EditArticle(ArticleModel model)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    _logger.LogWarning("Article edited model is not valid");
                    return View(model);
                }

                else
                {
                    var editedModel = _articleMapper.ArticleModelToArticleDto(model);
                    editedModel.Updated = DateTime.Now;
                    await _articleService.SaveChangedArticleAsync(editedModel);
                    _logger.LogInformation($"Article {model.Id} edited successfully");
                    return RedirectToAction("Index", "Home");
                }
            }
            catch (Exception ex)
            {
                HttpContext.Response.StatusCode = 404;
                return RedirectToAction("Error", "Home", new
                {
                    statusCode = HttpContext.Response.StatusCode,
                    errorMessage = "Такой новости нет :(<br>Почитайте что-нибудь ещё."
                });
            }
        }
    }
}

WebAppGNAggregator/Controllers/NewsletterController.cs
using EFDatabase;
using GNA.Services.Abstractions;
using Mappers.Mappers;
using MediatR;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace WebAppGNAggregator.Controllers
{
    [Authorize(Roles = "Admin")]
    public class NewsletterController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        private readonly INewsletterService _newsletterService;



        public NewsletterController(ILogger<HomeController> logger, INewsletterService newsletterService)
        {
            _logger = logger;
            _newsletterService = newsletterService;
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> SendNewsletters()
        {
            try
            {
                await _newsletterService.SendEmailsAsync();
                _logger.LogInformation("Sending successfully");
                return RedirectToAction("Index","Home");
            }
            catch (Exception ex)
            {
                //HttpContext.Response.StatusCode = 404;
                return RedirectToAction("Error", "Home", new
                {
                    statusCode = 500,
                    errorMessage = $"Непредвиденная ошибка при рассылке :(<br>{ex.Message}"
                });
            }
            return View();
        }
    }
}

WebAppGNAggregator/Views/Articles/AddArticle.cshtml
@model AddArticleModel

@{
    ViewBag.Title = "Add Article";
    Layout = "_Layout";
}

<h2>Add Article</h2>

<form asp-action="AddArticleProcessing" asp-controller="Articles" method="post">
    <div>
        <label asp-for="Title">Title</label>
        <input asp-for="Title" type="text" required />
    </div>
    <div>
        <label asp-for="Description">Description</label>
        <textarea asp-for="Description" required></textarea>
    </div>
    <div>
        <label asp-for="Rate">Rate</label>
        <input asp-for="Rate" type="number" />
    </div>
    <input type="submit" text="Submit" />
</form>

WebAppGNAggregator/Views/Articles/Aggregate.cshtml
@{
    ViewBag.Title = "Администрирование новостей";
    Layout = "_Layout";
}
<div class="cardGeneral shadow-lg">
    <div class="card shadow-lg mb-4">
        <h2>Администрирование новостей</h2>
    </div>

    <div class="mb-4">
        <form asp-action="AggregateProcessing" asp-controller="Articles" method="post">
            <div class="alert alert-warning" role="alert">
                Сбор новостей займет некоторое время...
            </div>
            <input class="btn btn400 " type="submit" value="Агрегировать" />
        </form>
    </div>

    <div class="mb-4">
        <form asp-action="Rate" asp-controller="Articles" method="post">
            <div class="alert alert-info" role="alert">
                Оценка выполняется в фоновом режиме. Сайтом можно пользоваться!
            </div>
            <input class="btn btn400 " type="submit" value="Оценить" />
        </form>
    </div>

    <div class="mb-4">
        <form asp-action="SendNewsletters" asp-controller="Newsletter" method="post">
            <div class="alert alert-info" role="alert">
                Рассылка НЕ занимает много времени
            </div>
            <input class="btn btn400 " type="submit" value="Рассылка" />
        </form>
    </div>
</div>

WebAppGNAggregator/Views/Articles/Details.cshtml
@using DataConvert.DTO
@using System.Security.Claims
@model ArticleModel

@{
    ViewBag.Title = Model.Title;
    Layout = "_Layout";
}

<div class="cardGeneral shadow-lg">
    <div class="card shadow-lg"><h2>@Model.Title</h2></div>
    <hr>
    <p>
        <span>Создано @Model.Created</span>
    </p>

    @if (Model.Updated != null)
    {
        <p>
            <span>Изменено @Model.Updated</span>
        </p>
    }

    <p>
        <h6>Рейтинг позитивности: @Model.PositivityRate</h6>
    </p>

    <div>

        <div>
            <p>
                @Model.Content
            </p>
        </div>
    </div>

    @if (User.Claims.Any(c => c.Type == ClaimTypes.Role && c.Value == "Admin"))
    {
        <div class="mx-auto btn-group">
            <form asp-action="EditArticle" asp-controller="Articles" method="get">
            <input type="hidden" name="Id" value="@Model.Id" />
            <button type="submit" class="btn btn400">Редактировать</button>
        </form>

        <form asp-action="Delete" asp-controller="Articles" method="post">
            <input type="hidden" name="Id" value="@Model.Id" />
            <button type="button" class="btn btn400" onclick="confirmDelete()">Удалить</button>
        </form>
        
        <form>
            <a class=" btn  btn400" asp-action="Index" asp-controller="Home">На главную</a>
        </form>
    </div>
    }
</div>

<script>
    function confirmDelete() {
        const userConfirmed = confirm("Вы уверены, что хотите удалить эту запись?");
        if (userConfirmed) {
            const form = event.target.closest('form');
            form.submit();
        }
    }
</script>

WebAppGNAggregator/Views/Articles/EditArticle.cshtml
@model ArticleModel

@{
    ViewBag.Title = "Редактирование новости";
    Layout = "_Layout";
}

<form class="cardGeneral shadow-lg p-4" asp-action="EditArticle" asp-controller="Articles" method="post">

    <div class="card shadow-lg"><h2 class="text-center mb-4">Редактирование новости</h2></div>

    <input asp-for="Id" type="hidden" />
    <input asp-for="Created" type="hidden" />
    <input asp-for="SourceName" type="hidden" />


    <div asp-validation-summary="ModelOnly" class="text-danger"></div>

    <span asp-validation-for="Title" class="text-error"></span>

    <div class="form-group mb-3">
        <label asp-for="Title" class="form-label">Заголовок</label>
        <input asp-for="Title" type="text" class="form-control" placeholder="Заголовок" required />
    </div>
    
    <div class="form-group mb-3">
        <label asp-for="Description" class="form-label">Описание</label>
        <textarea asp-for="Description" class="form-control" rows="4" placeholder="Описание"></textarea>
    </div>
    

    <span asp-validation-for="Content" class="text-error"></span>
    <div class="form-group mb-3">
        <label asp-for="Content" class="form-label">Текст</label>
        <textarea asp-for="Content" class="form-control" rows="5" placeholder="Текст новости" required></textarea>
    </div>
    

    <span asp-validation-for="ImageUrl" class="text-error"></span>
    <div class="form-group mb-3">
        <label asp-for="ImageUrl" class="form-label">Url изображения</label>
        <textarea asp-for="ImageUrl" class="form-control" rows="3" placeholder="URL изображения"></textarea>
    </div>
    
    <span asp-validation-for="PositivityRate" class="text-error"></span>

    <div class="d-flex align-items-center mb-3">
        <label asp-for="PositivityRate" class="form-label  me-3" style="white-space: nowrap">Рейтинг позитивности   </label>
        <input asp-for="PositivityRate" type="number" class="form-control" placeholder="5" />
        
    </div>
    
    <div class="btn-group">
        <button type="submit" class="btn btn400">Сохранить</button>
        <a class="btn btn400" asp-action="Details" asp-controller="Articles" asp-route-id="@Model.Id">Отмена</a>
    </div>
</form>